---
- name: PLAY1_1
  hosts: my
  become: yes

  tasks:
  - name: Make new directory
    file:
      path: /home/ivan/apache/
      state: directory

  - name: Download a file
    get_url:
      url: "https://dlcdn.apache.org/kafka/3.9.1/kafka_2.13-3.9.1.tgz"
      dest: "/home/ivan/apache/kafka_2.13-3.9.1.tgz"

  - name: Распаковка архива
    unarchive:
      src: /home/ivan/apache/kafka_2.13-3.9.1.tgz  # Путь к архиву
      dest: /home/ivan/apache/     # Целевая директория
      remote_src: yes                # Распаковывать на удаленном хосте (если архив уже там)
      owner: ivan                    # Владелец распакованных файлов
      group: ivan                   # Группа распакованных файлов
      mode: '0755'                   # Права доступа к распакованным файлам